### ISSUE TITLE
Error: ''NoneType' object has no attribute 'squeeze''

### ISSUE THREAD

**Issue by ipoppy07** [mrdbourke/pytorch-deep-learning#1039]
*START OF TRACEBACK*
Traceback (most recent call last):
  File "/Applications/Data/Packages/stable-diffusion-webui/extensions/sd-webui-deforum/scripts/deforum_helpers/run_deforum.py", line 116, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root)
  File "/Applications/Data/Packages/stable-diffusion-webui/extensions/sd-webui-deforum/scripts/deforum_helpers/render.py", line 415, in render_animation
    prev_img, depth = anim_frame_warp(prev_img, args, anim_args, keys, frame_idx, depth_model, depth=None, device=root.device, half_precision=root.half_precision)
  File "/Applications/Data/Packages/stable-diffusion-webui/extensions/sd-webui-deforum/scripts/deforum_helpers/animation.py", line 177, in anim_frame_warp
    depth = depth_model.predict(prev_img_cv2, anim_args.midas_weight, half_precision)
  File "/Applications/Data/Packages/stable-diffusion-webui/extensions/sd-webui-deforum/scripts/deforum_helpers/depth.py", line 104, in predict
    depth_tensor = self.midas_depth.predict(prev_img_cv2, half_precision)
  File "/Applications/Data/Packages/stable-diffusion-webui/extensions/sd-webui-deforum/scripts/deforum_helpers/depth_midas.py", line 82, in predict
    ).squeeze().cpu().numpy()
AttributeError: 'NoneType' object has no attribute 'squeeze'

**Comment by pritesh2000** [comment]
Can you provide code ?

**Comment by pritesh2000** [comment]
It typically means that, Your tensor is getting NoneType object because of that It can't be squeeze.
Possibly you explicitly provided some variable which is NoneType or created some function which returns NoneType object.
