### ISSUE TITLE
loaded model mismatch error

### ISSUE THREAD

**Issue by Mudassir-A** [mrdbourke/pytorch-deep-learning#1110]
> help me solve this code please!

while completing the exercises, i encounter this error. even by copying the exact code as given in [Example solutions notebook for 05](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/05_pytorch_going_modular_exercise_solutions.ipynb) on this section - **3 .Create a script to predict (such as predict.py) on a target image given a file path with a saved model.** 

Error: 
``` bash
[INFO] Predicting on data/pizza_steak_sushi/test/sushi/175783.jpg
[INFO] Loading in model from: models/going_modular_model.pth
E:\codebase\Python\PyTorch\learnpytorch.io\going_modular\predict.py:43: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(filepath))
Traceback (most recent call last):
  File "E:\codebase\Python\PyTorch\learnpytorch.io\going_modular\predict.py", line 85, in <module>
    predict_on_image()
  File "E:\codebase\Python\PyTorch\learnpytorch.io\going_modular\predict.py", line 51, in predict_on_image
    model = load_model(filepath)
            ^^^^^^^^^^^^^^^^^^^^
  File "E:\codebase\Python\PyTorch\learnpytorch.io\going_modular\predict.py", line 43, in load_model
        size mismatch for conv_block_1.0.weight: copying a param with shape torch.Size([10, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3]).
        size mismatch for conv_block_1.0.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([128]).        
        size mismatch for conv_block_1.2.weight: copying a param with shape torch.Size([10, 10, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
        size mismatch for conv_block_1.2.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([128]).        
        size mismatch for conv_block_2.0.weight: copying a param with shape torch.Size([10, 10, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
        size mismatch for conv_block_2.0.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([128]).        
        size mismatch for conv_block_2.2.weight: copying a param with shape torch.Size([10, 10, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
        size mismatch for conv_block_2.2.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([128]).        
        size mismatch for classifier.1.weight: copying a param with shape torch.Size([3, 1690]) from checkpoint, the shape in current model is torch.Size([3, 21632]).
```

**Comment by pritesh2000** [comment]
Hey @Mudassir-A 
I have run the provided code. It is working fine.

Can you provide your code? 
It is better to figure out if we have the source.
